import * as fs from 'fs';
import * as path from 'path';
import simpleGit, { SimpleGit } from 'simple-git';
import { WorkspaceResolver } from '../../../../../../../infrastructure/workspace/WorkspaceResolver';
import { UserContext } from '../../../../../../../core/types/user';
import { GitHubAuthService } from '../../../../../auth/GitHubAuthService';
import { GitHelper } from '../../helper/GitHelper';
import { GitignoreGenerator } from '../helpers/GitignoreGenerator';
import { GitNotFoundError, GitOperationError } from '../../errors';

/**
 * BaseGitSetupOperation
 * 
 * Base class for InitOperation.
 * Provides common methods for Git initialization, commit creation,
 * GitHub repository creation, and rollback.
 * 
 * Initializes Git in projectPath/codebase/ (the main worktree).
 * No branch checkout is performed in the main worktree — it always stays on the base branch.
 */
export abstract class BaseGitSetupOperation {
  constructor(
    protected readonly workspaceResolver: WorkspaceResolver,
    protected readonly githubAuthService?: GitHubAuthService,
    protected readonly onIndexingTrigger?: (projectId: string, codebasePath: string, userContext: UserContext, feedbackFeature?: string) => void
  ) {}

  protected async loadConfig(projectId: string, userContext: UserContext): Promise<{ config: any; projectPath: string; codebasePath: string }> {
    const projectPath = this.workspaceResolver.getProjectPath(userContext, projectId);
    const configPath = path.join(projectPath, 'config.json');
    
    if (!fs.existsSync(configPath)) {
      throw new GitNotFoundError('Project config not found');
    }

    const config = JSON.parse(await fs.promises.readFile(configPath, 'utf-8'));
    
    if (!config.githubRepo) {
      throw new GitOperationError('GitHub repository not configured in project config');
    }

    // Use centralized codebase path resolution (main worktree for init/publish operations)
    const codebasePath = this.workspaceResolver.getCodebasePath(userContext, projectId);

    return { config, projectPath, codebasePath };
  }

  protected async prepareCodebase(codebasePath: string, projectId: string): Promise<boolean> {
    if (!fs.existsSync(codebasePath)) {
      await fs.promises.mkdir(codebasePath, { recursive: true });
    }

    const files = await fs.promises.readdir(codebasePath);
    const hasFiles = files.length > 0;

    if (!hasFiles) {
      const readmePath = path.join(codebasePath, 'README.md');
      const readmeContent = `# ${projectId}\n\nGenerated by ANT\n\n## Getting Started\n\nThis project was created using ANT CLI.\n`;
      await fs.promises.writeFile(readmePath, readmeContent, 'utf-8');
    }

    return hasFiles;
  }

  protected async initializeGit(codebasePath: string, baseBranch: string, userContext: UserContext): Promise<SimpleGit> {
    const git = simpleGit({
      baseDir: codebasePath,
      binary: 'git',
      maxConcurrentProcesses: 6
    });
    
    await git.init([`--initial-branch=${baseBranch}`]);
    
    const gitDir = path.join(codebasePath, '.git');
    if (!fs.existsSync(gitDir)) {
      throw new GitOperationError(`Git initialization failed: .git not found in ${codebasePath}`);
    }

    await GitHelper.ensureSafeDirectory(codebasePath);
    await GitHelper.ensureUserConfig(git, userContext);
    
    console.log(`[${this.operationName}] ✅ Git initialized`);
    return git;
  }

  protected async createGitignore(codebasePath: string): Promise<void> {
    const gitignorePath = path.join(codebasePath, '.gitignore');
    
    if (!fs.existsSync(gitignorePath)) {
      console.log(`[${this.operationName}] Creating .gitignore at ${gitignorePath}`);
      const gitignoreContent = await GitignoreGenerator.generate(codebasePath);
      await fs.promises.writeFile(gitignorePath, gitignoreContent, 'utf-8');
      console.log(`[${this.operationName}] ✅ .gitignore created`);
    } else {
      console.log(`[${this.operationName}] .gitignore already exists, skipping creation`);
    }
  }

  protected async createInitialCommit(git: SimpleGit, codebasePath: string, hasFiles: boolean): Promise<void> {
    await git.add('.');
    const status = await git.status();
    
    if (status.files.length > 0) {
      const commitMessage = hasFiles 
        ? 'Initial commit with existing code'
        : 'Initial commit from ANT';
      await git.commit(commitMessage);
      console.log(`[${this.operationName}] ✅ Initial commit created: "${commitMessage}"`);
    } else {
      const gitkeepPath = path.join(codebasePath, '.gitkeep');
      await fs.promises.writeFile(gitkeepPath, '');
      await git.add('.gitkeep');
      await git.commit('Initial commit from ANT');
      console.log(`[${this.operationName}] ✅ Initial commit created (empty)`);
    }
  }

  protected async ensureDefaultBranch(git: SimpleGit, baseBranch: string): Promise<string> {
    let defaultBranch = baseBranch;
    
    try {
      defaultBranch = await git.raw(['config', '--get', 'init.defaultBranch']);
      defaultBranch = defaultBranch.trim() || baseBranch;
    } catch {
      defaultBranch = baseBranch;
    }

    const currentBranch = await git.revparse(['--abbrev-ref', 'HEAD']);
    if (currentBranch.trim() !== defaultBranch) {
      await git.branch(['-M', defaultBranch]);
      console.log(`[${this.operationName}] Renamed branch to ${defaultBranch}`);
    }

    return defaultBranch;
  }

  protected async createGitHubRepo(githubRepo: string, projectId: string, userContext: UserContext): Promise<void> {
    console.log(`[${this.operationName}] Creating GitHub repository at ${githubRepo}...`);
    
    try {
      await this.githubAuthService!.createRepo(
        userContext,
        githubRepo,
        {
          description: `${projectId} - Generated by ANT`,
          private: true
        }
      );
      console.log(`[${this.operationName}] ✅ GitHub repository created`);
    } catch (error: any) {
      const errorMsg = error.message || error.toString();
      // Only ignore "already exists" errors — the repo is usable in that case
      if (errorMsg.includes('already exists') || errorMsg.includes('name already exists')) {
        console.log(`[${this.operationName}] GitHub repo already exists, continuing...`);
        return;
      }
      // All other errors must propagate so the caller sees the real failure
      throw error;
    }
  }

  protected async addRemoteAndPush(
    git: SimpleGit,
    defaultBranch: string,
    config: any,
    userContext: UserContext
  ): Promise<void> {
    const credentialContext = {
      org: userContext.organizationId,
      user: userContext.userId
    };
    const authenticatedUrl = await this.githubAuthService!.buildAuthenticatedUrl(
      credentialContext,
      config.githubRepo
    );

    await git.addRemote('origin', authenticatedUrl);
    console.log(`[${this.operationName}] ✅ Remote added`);

    console.log(`[${this.operationName}] Pushing to remote...`);
    await git.push(['-u', 'origin', defaultBranch]);
    await git.branch(['--set-upstream-to', `origin/${defaultBranch}`, defaultBranch]);
    console.log(`[${this.operationName}] ✅ Pushed to remote: ${defaultBranch}`);
  }

  protected async triggerIndexing(projectId: string, codebasePath: string, userContext: UserContext): Promise<void> {
    console.log(`[${this.operationName}] 🗑️  Clearing Vector DB for fresh start...`);
    try {
      const { AdapterFactory } = await import('../../../../../../../infrastructure/adapters/AdapterFactory');
      const vectorDB = AdapterFactory.createMemoryAdapter();
      await vectorDB.clear(projectId);
      console.log(`[${this.operationName}] ✅ Vector DB cleared`);
    } catch (error) {
      console.warn(`[${this.operationName}] ⚠️  Could not clear Vector DB:`, error);
    }

    if (this.onIndexingTrigger) {
      console.log(`[${this.operationName}] 🔍 Starting codebase indexing...`);
      const feedbackFeature = 'main';
      
      setImmediate(() => {
        this.onIndexingTrigger!(projectId, codebasePath, userContext, feedbackFeature);
      });
      
      console.log(`[${this.operationName}] ✅ Complete, indexing started in background`);
    }
  }

  protected async readExistingFeatures(projectPath: string): Promise<string[]> {
    const { FeatureCodebaseBackup } = await import('../../worktree/FeatureCodebaseBackup');
    const features = await FeatureCodebaseBackup.readExistingFeatures(projectPath);
    if (features.length > 0) {
      console.log(`[${this.operationName}] Found ${features.length} existing feature(s): ${features.join(', ')}`);
    }
    return features;
  }

  protected async seedMainCodebase(
    projectId: string,
    seedFeature: string,
    codebasePath: string,
    userContext: UserContext
  ): Promise<void> {
    if (fs.existsSync(codebasePath)) {
      const existingFiles = await fs.promises.readdir(codebasePath);
      if (existingFiles.length > 0) {
        console.log(`[${this.operationName}] Main codebase already has files, skipping seed`);
        return;
      }
    }

    const featureCodebasePath = this.workspaceResolver.getCodebasePath(userContext, projectId, seedFeature);
    if (!fs.existsSync(featureCodebasePath)) return;

    const files = await fs.promises.readdir(featureCodebasePath);
    const nonGitFiles = files.filter(f => f !== '.git');
    if (nonGitFiles.length === 0) return;

    await fs.promises.mkdir(codebasePath, { recursive: true });
    console.log(`[${this.operationName}] Seeding main codebase from feature: ${seedFeature}`);
    for (const item of nonGitFiles) {
      await fs.promises.cp(
        path.join(featureCodebasePath, item),
        path.join(codebasePath, item),
        { recursive: true }
      );
    }
    console.log(`[${this.operationName}] Main codebase seeded with ${nonGitFiles.length} items from ${seedFeature}`);
  }

  protected async rollback(codebasePath: string): Promise<void> {
    try {
      const gitDir = path.join(codebasePath, '.git');
      if (fs.existsSync(gitDir)) {
        await fs.promises.rm(gitDir, { recursive: true, force: true });
        console.log(`[${this.operationName}] 🔄 Rolled back: .git directory removed`);
      }

      const gitignorePath = path.join(codebasePath, '.gitignore');
      if (fs.existsSync(gitignorePath)) {
        await fs.promises.unlink(gitignorePath);
        console.log(`[${this.operationName}] 🔄 Rolled back: .gitignore removed`);
      }

      console.log(`[${this.operationName}] ✅ Rollback complete`);
    } catch (error) {
      console.error(`[${this.operationName}] ⚠️ Rollback failed:`, error);
    }
  }

  /** Subclass identifier used in log messages */
  protected abstract get operationName(): string;

  /** Main execution method */
  abstract execute(projectId: string, userContext: UserContext, ...args: any[]): Promise<any>;
}
