import * as fs from 'fs';
import * as path from 'path';
import simpleGit, { SimpleGit } from 'simple-git';
import { WorkspaceResolver } from '../../../../../../../core/config/WorkspacePathResolver';
import { isVectorDbEnabled } from '../../../../../../../core/config/vectorDbCapability';
import { UserContext } from '../../../../../../../core/types/user';
import { GitHubAuthService, GitHubRepoCreateError } from '../../../../../auth/GitHubAuthService';
import { GitHelper } from '../../helper/GitHelper';
import { GitignoreGenerator } from '../helpers/GitignoreGenerator';
import {
  GitAuthError,
  GitConfigError,
  GitConflictError,
  GitNetworkError,
  GitNotFoundError,
  GitOperationError,
} from '../../errors';
import { logger } from '../../../../../../../utils/logger';

export type GitBootstrapFailureReason =
  | 'permissionDenied'
  | 'gitBinaryMissing'
  | 'gitInitFailed'
  | 'gitCommitFailed'
  | 'safeDirectory'
  | 'userConfig'
  | 'commitMissing'
  | 'unknown';

export interface GitBootstrapResult {
  created: boolean;
  ready: boolean;
  reason?: GitBootstrapFailureReason;
  error?: string;
}

export interface GitBootstrapRequest {
  projectId: string;
  codebasePath: string;
  baseBranch: string;
  userContext: UserContext;
}

/**
 * BaseGitSetupOperation
 * 
 * Base class for InitOperation.
 * Provides common methods for Git initialization, commit creation,
 * GitHub repository creation, and rollback.
 * 
 * Initializes Git in projectPath/codebase/ (the main worktree).
 * No branch checkout is performed in the main worktree — it always stays on the base branch.
 */
export abstract class BaseGitSetupOperation {
  constructor(
    protected readonly workspaceResolver: WorkspaceResolver,
    protected readonly githubAuthService?: GitHubAuthService,
    protected readonly onIndexingTrigger?: (projectId: string, codebasePath: string, userContext: UserContext, feedbackFeature?: string) => void
  ) {}

  protected async loadConfig(projectId: string, userContext: UserContext): Promise<{ config: any; projectPath: string; codebasePath: string }> {
    const projectPath = this.workspaceResolver.getProjectPath(userContext, projectId);
    const configPath = path.join(projectPath, 'config.json');
    
    if (!fs.existsSync(configPath)) {
      throw new GitNotFoundError('Project config not found');
    }

    const config = JSON.parse(await fs.promises.readFile(configPath, 'utf-8'));
    
    if (!config.githubRepo) {
      throw new GitOperationError('GitHub repository not configured in project config');
    }

    // Use centralized codebase path resolution (main worktree for init/publish operations)
    const codebasePath = this.workspaceResolver.getCodebasePath(userContext, projectId);

    return { config, projectPath, codebasePath };
  }

  protected async prepareCodebase(codebasePath: string, projectId: string): Promise<boolean> {
    if (!fs.existsSync(codebasePath)) {
      await fs.promises.mkdir(codebasePath, { recursive: true });
    }

    const files = await fs.promises.readdir(codebasePath);
    const hasFiles = files.length > 0;

    if (!hasFiles) {
      const readmePath = path.join(codebasePath, 'README.md');
      const readmeContent = `# ${projectId}\n\nGenerated by ANT\n\n## Getting Started\n\nThis project was created using ANT CLI.\n`;
      await fs.promises.writeFile(readmePath, readmeContent, 'utf-8');
    }

    return hasFiles;
  }

  protected async initializeGit(codebasePath: string, baseBranch: string, userContext: UserContext): Promise<SimpleGit> {
    const git = simpleGit({
      baseDir: codebasePath,
      binary: 'git',
      maxConcurrentProcesses: 6
    });
    
    await git.init([`--initial-branch=${baseBranch}`]);
    
    const gitDir = path.join(codebasePath, '.git');
    if (!fs.existsSync(gitDir)) {
      throw new GitOperationError(`Git initialization failed: .git not found in ${codebasePath}`);
    }

    await GitHelper.ensureSafeDirectory(codebasePath);
    await GitHelper.ensureUserConfig(git, userContext);
    
    console.log(`[${this.operationName}] ✅ Git initialized`);
    return git;
  }

  protected async createGitignore(codebasePath: string): Promise<void> {
    const gitignorePath = path.join(codebasePath, '.gitignore');
    
    if (!fs.existsSync(gitignorePath)) {
      console.log(`[${this.operationName}] Creating .gitignore at ${gitignorePath}`);
      const gitignoreContent = await GitignoreGenerator.generate(codebasePath);
      await fs.promises.writeFile(gitignorePath, gitignoreContent, 'utf-8');
      console.log(`[${this.operationName}] ✅ .gitignore created`);
    } else {
      console.log(`[${this.operationName}] .gitignore already exists, skipping creation`);
    }
  }

  protected async createInitialCommit(git: SimpleGit, codebasePath: string, hasFiles: boolean): Promise<void> {
    await git.add('.');
    const status = await git.status();
    
    if (status.files.length > 0) {
      const commitMessage = hasFiles 
        ? 'Initial commit with existing code'
        : 'Initial commit from ANT';
      await git.commit(commitMessage);
      console.log(`[${this.operationName}] ✅ Initial commit created: "${commitMessage}"`);
    } else {
      const gitkeepPath = path.join(codebasePath, '.gitkeep');
      await fs.promises.writeFile(gitkeepPath, '');
      await git.add('.gitkeep');
      await git.commit('Initial commit from ANT');
      console.log(`[${this.operationName}] ✅ Initial commit created (empty)`);
    }
  }

  protected async ensureDefaultBranch(git: SimpleGit, baseBranch: string): Promise<string> {
    let defaultBranch = baseBranch;
    
    try {
      defaultBranch = await git.raw(['config', '--get', 'init.defaultBranch']);
      defaultBranch = defaultBranch.trim() || baseBranch;
    } catch {
      defaultBranch = baseBranch;
    }

    const currentBranch = await git.revparse(['--abbrev-ref', 'HEAD']);
    if (currentBranch.trim() !== defaultBranch) {
      await git.branch(['-M', defaultBranch]);
      console.log(`[${this.operationName}] Renamed branch to ${defaultBranch}`);
    }

    return defaultBranch;
  }

  protected async createGitHubRepo(githubRepo: string, projectId: string, userContext: UserContext): Promise<void> {
    console.log(`[${this.operationName}] Creating GitHub repository at ${githubRepo}...`);
    
    try {
      await this.githubAuthService!.createRepo(
        userContext,
        githubRepo,
        {
          description: `${projectId} - Generated by ANT`,
          private: true
        }
      );
      console.log(`[${this.operationName}] ✅ GitHub repository created`);
    } catch (error: any) {
      if (error instanceof GitHubRepoCreateError && error.isAlreadyExistsError()) {
        console.log(`[${this.operationName}] GitHub repo already exists, continuing...`);
        return;
      }
      if (error instanceof GitHubRepoCreateError) {
        const requestIdSuffix = error.requestId ? ` (request_id=${error.requestId})` : '';
        if (error.statusCode === 401 || error.statusCode === 403) {
          throw new GitAuthError(
            `GitHub authentication failed while creating ${githubRepo}: ${error.apiMessage}${requestIdSuffix}`,
            { retryable: false }
          );
        }
        if (error.statusCode === 409) {
          throw new GitConflictError(
            `GitHub repository conflict for ${githubRepo}: ${error.apiMessage}${requestIdSuffix}`,
            { retryable: false, suggestedAction: 'reconfigureRepo' }
          );
        }
        if (error.statusCode === 422) {
          throw new GitConfigError(
            `GitHub rejected repository settings for ${githubRepo}: ${error.apiMessage}${requestIdSuffix}`,
            { retryable: false, suggestedAction: 'reconfigureRepo' }
          );
        }
        if (error.statusCode >= 500) {
          throw new GitNetworkError(
            `GitHub server error while creating ${githubRepo}: ${error.apiMessage}${requestIdSuffix}`,
            { retryable: true }
          );
        }
        throw new GitOperationError(
          `Failed to create GitHub repository ${githubRepo}: ${error.apiMessage}${requestIdSuffix}`,
          error.statusCode
        );
      }

      const errorMsg = error instanceof Error ? error.message : String(error);
      throw new GitOperationError(`Failed to create GitHub repository ${githubRepo}: ${errorMsg}`, 'unknown');
    }
  }

  protected async addRemoteAndPush(
    git: SimpleGit,
    defaultBranch: string,
    config: any,
    userContext: UserContext
  ): Promise<void> {
    const credentialContext = {
      org: userContext.organizationId,
      user: userContext.userId
    };
    const authenticatedUrl = await this.githubAuthService!.buildAuthenticatedUrl(
      credentialContext,
      config.githubRepo
    );

    await git.addRemote('origin', authenticatedUrl);
    console.log(`[${this.operationName}] ✅ Remote added`);

    console.log(`[${this.operationName}] Pushing to remote...`);
    await git.push(['-u', 'origin', defaultBranch]);
    await git.branch(['--set-upstream-to', `origin/${defaultBranch}`, defaultBranch]);
    console.log(`[${this.operationName}] ✅ Pushed to remote: ${defaultBranch}`);
  }

  protected async triggerIndexing(projectId: string, codebasePath: string, userContext: UserContext): Promise<void> {
    if (!isVectorDbEnabled()) {
      console.log(`[${this.operationName}] ℹ️  Vector DB disabled (ANT_VECTOR_DB_ENABLED=false) — skipping clear + indexing.`);
      return;
    }

    console.log(`[${this.operationName}] 🗑️  Clearing Vector DB for fresh start...`);
    try {
      const { AdapterFactory } = await import('../../../../../../../infrastructure/adapters/AdapterFactory');
      const vectorDB = AdapterFactory.createMemoryAdapter();
      await vectorDB.clear(projectId);
      console.log(`[${this.operationName}] ✅ Vector DB cleared`);
    } catch (error) {
      console.warn(`[${this.operationName}] ⚠️  Could not clear Vector DB:`, error);
    }

    if (this.onIndexingTrigger) {
      console.log(`[${this.operationName}] 🔍 Starting codebase indexing...`);
      const feedbackFeature = 'main';
      
      setImmediate(() => {
        this.onIndexingTrigger!(projectId, codebasePath, userContext, feedbackFeature);
      });
      
      console.log(`[${this.operationName}] ✅ Complete, indexing started in background`);
    }
  }

  protected async readExistingFeatures(projectPath: string): Promise<string[]> {
    const { FeatureCodebaseBackup } = await import('../../worktree/FeatureCodebaseBackup');
    const features = await FeatureCodebaseBackup.readExistingFeatures(projectPath);
    if (features.length > 0) {
      console.log(`[${this.operationName}] Found ${features.length} existing feature(s): ${features.join(', ')}`);
    }
    return features;
  }

  protected async seedMainCodebase(
    projectId: string,
    seedFeature: string,
    codebasePath: string,
    userContext: UserContext
  ): Promise<void> {
    if (fs.existsSync(codebasePath)) {
      const existingFiles = await fs.promises.readdir(codebasePath);
      if (existingFiles.length > 0) {
        console.log(`[${this.operationName}] Main codebase already has files, skipping seed`);
        return;
      }
    }

    const featureCodebasePath = this.workspaceResolver.getCodebasePath(userContext, projectId, seedFeature);
    if (!fs.existsSync(featureCodebasePath)) return;

    const files = await fs.promises.readdir(featureCodebasePath);
    const nonGitFiles = files.filter(f => f !== '.git');
    if (nonGitFiles.length === 0) return;

    await fs.promises.mkdir(codebasePath, { recursive: true });
    console.log(`[${this.operationName}] Seeding main codebase from feature: ${seedFeature}`);
    for (const item of nonGitFiles) {
      await fs.promises.cp(
        path.join(featureCodebasePath, item),
        path.join(codebasePath, item),
        { recursive: true }
      );
    }
    console.log(`[${this.operationName}] Main codebase seeded with ${nonGitFiles.length} items from ${seedFeature}`);
  }

  protected async rollback(codebasePath: string): Promise<void> {
    try {
      const gitDir = path.join(codebasePath, '.git');
      if (fs.existsSync(gitDir)) {
        await fs.promises.rm(gitDir, { recursive: true, force: true });
        console.log(`[${this.operationName}] 🔄 Rolled back: .git directory removed`);
      }

      const gitignorePath = path.join(codebasePath, '.gitignore');
      if (fs.existsSync(gitignorePath)) {
        await fs.promises.unlink(gitignorePath);
        console.log(`[${this.operationName}] 🔄 Rolled back: .gitignore removed`);
      }

      console.log(`[${this.operationName}] ✅ Rollback complete`);
    } catch (error) {
      console.error(`[${this.operationName}] ⚠️ Rollback failed:`, error);
    }
  }

  /** Subclass identifier used in log messages */
  protected abstract get operationName(): string;

  /** Main execution method */
  abstract execute(projectId: string, userContext: UserContext, ...args: any[]): Promise<any>;
}

/**
 * GitBootstrapSSOT
 *
 * Reuses the already battle-tested setup steps from BaseGitSetupOperation and
 * exposes them as a shared bootstrap entry point for project/feature/remote flows.
 */
export class GitBootstrapSSOT extends BaseGitSetupOperation {
  constructor(
    workspaceResolver: WorkspaceResolver,
    private readonly sourceComponent = 'GitBootstrapSSOT'
  ) {
    super(workspaceResolver);
  }

  protected get operationName(): string {
    return this.sourceComponent;
  }

  async execute(_projectId: string, _userContext: UserContext, ..._args: any[]): Promise<never> {
    throw new Error('GitBootstrapSSOT.execute is not used directly');
  }

  async ensureLocalGitReady(request: GitBootstrapRequest): Promise<GitBootstrapResult> {
    const { projectId, codebasePath, baseBranch, userContext } = request;
    let created = false;
    let seededInitialCommit = false;

    try {
      await fs.promises.mkdir(codebasePath, { recursive: true });

      let git = GitHelper.getGitInstanceSafe(codebasePath);

      if (!git) {
        const hasFiles = await this.prepareCodebase(codebasePath, projectId);
        git = await this.initializeGit(codebasePath, baseBranch, userContext);
        await this.createGitignore(codebasePath);
        await this.createInitialCommit(git, codebasePath, hasFiles);
        created = true;
        seededInitialCommit = true;
      } else {
        await GitHelper.ensureSafeDirectory(codebasePath);
        await GitHelper.ensureUserConfig(git, userContext);
        await this.createGitignore(codebasePath);

        const hasCommit = await this.hasCommit(git);
        if (!hasCommit) {
          const hasFiles = await this.hasNonGitFiles(codebasePath);
          await this.createInitialCommit(git, codebasePath, hasFiles);
          seededInitialCommit = true;
        }
      }

      const ready = await this.validateReady(codebasePath);
      if (!ready) {
        logger.error(
          'gitBootstrapFailure',
          {
            component: this.sourceComponent,
            organizationId: userContext.organizationId,
            userId: userContext.userId,
            projectId,
          },
          {
            codebasePath,
            baseBranch,
            reason: 'commitMissing',
          }
        );
        return {
          created,
          ready: false,
          reason: 'commitMissing',
          error: 'git repository exists but has no commit',
        };
      }

      if (created || seededInitialCommit) {
        logger.info(
          'gitBootstrapRecovered',
          {
            component: this.sourceComponent,
            organizationId: userContext.organizationId,
            userId: userContext.userId,
            projectId,
          },
          {
            codebasePath,
            baseBranch,
            created,
            seededInitialCommit,
          }
        );
      }

      return { created, ready: true };
    } catch (error) {
      const reason = this.classifyFailureReason(error);
      const message = error instanceof Error ? error.message : String(error);

      logger.error(
        'gitBootstrapFailure',
        {
          component: this.sourceComponent,
          organizationId: userContext.organizationId,
          userId: userContext.userId,
          projectId,
        },
        {
          codebasePath,
          baseBranch,
          reason,
          error: message,
        }
      );

      return {
        created,
        ready: false,
        reason,
        error: message,
      };
    }
  }

  async ensureLocalGitReadyOrThrow(request: GitBootstrapRequest): Promise<GitBootstrapResult> {
    const result = await this.ensureLocalGitReady(request);
    if (result.ready) {
      return result;
    }

    const reason = result.reason ?? 'unknown';
    throw new GitConfigError(
      `Failed to prepare local git repository (${reason}): ${result.error ?? 'unknown error'}`,
      {
        retryable: false,
      }
    );
  }

  private async validateReady(codebasePath: string): Promise<boolean> {
    const git = GitHelper.getGitInstanceSafe(codebasePath);
    if (!git) return false;
    return this.hasCommit(git);
  }

  private async hasCommit(git: SimpleGit): Promise<boolean> {
    try {
      const log = await git.log({ maxCount: 1 });
      return Boolean(log.latest);
    } catch {
      return false;
    }
  }

  private async hasNonGitFiles(codebasePath: string): Promise<boolean> {
    const files = await fs.promises.readdir(codebasePath);
    return files.some((entry) => entry !== '.git');
  }

  private classifyFailureReason(error: unknown): GitBootstrapFailureReason {
    const message = (error instanceof Error ? error.message : String(error)).toLowerCase();

    if (message.includes('permission denied') || message.includes('eacces') || message.includes('eperm')) {
      return 'permissionDenied';
    }
    if (
      message.includes('git') &&
      (message.includes('not found') || message.includes('enoent') || message.includes('spawn'))
    ) {
      return 'gitBinaryMissing';
    }
    if (message.includes('safe.directory') || message.includes('dubious ownership')) {
      return 'safeDirectory';
    }
    if (message.includes('user.email') || message.includes('user.name') || message.includes('author identity')) {
      return 'userConfig';
    }
    if (message.includes('commit')) {
      return 'gitCommitFailed';
    }
    if (message.includes('init') || message.includes('initialize')) {
      return 'gitInitFailed';
    }
    return 'unknown';
  }
}
