/**
 * Token Usage Utility Functions
 *
 * Architecture doc: docs/architecture/13-token-usage-tracking.md
 *
 * DESIGN PRINCIPLE: Input and Output are fundamentally different cost categories.
 *   - Input: $3/MTok (Sonnet 4), cacheable, high volume, optimization target
 *   - Output: $15/MTok (Sonnet 4), NOT cacheable, lower volume, 5x more expensive
 *   → NEVER sum them into a single "total" — it's like adding different currencies.
 *
 * Anthropic API field semantics (confirmed via official docs):
 *   - input_tokens = tokens AFTER last cache breakpoint (cache-miss only)
 *   - cache_read_input_tokens = tokens served from cache
 *   - cache_creation_input_tokens = tokens written to cache
 *   - total input = input_tokens + cache_read + cache_creation
 *   See: https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching
 */

import { TaskTokenUsage } from '@/domain/models/types';
import {
  computeJobCostUsd,
  computeCallCostUsdSafe,
  computeModelCostBreakdownUsd,
  usdToMicroCredits,
  microCreditsToCredits,
  type TokenUsageByModel,
} from '@ant/shared';

// ============================================
// Anthropic Cache Pricing Multipliers
// (relative to base input token price)
// ============================================

/** Cache creation costs 25% more than base input price */
export const CACHE_CREATION_MULTIPLIER = 1.25;
/** Cache read costs 10% of base input price (90% discount) */
export const CACHE_READ_MULTIPLIER = 0.10;

// ============================================
// Metrics Interface
// ============================================

export interface TokenUsageMetrics {
  // === Input Tokens (cacheable, high volume) ===
  /** Total input tokens processed by API = new + cacheRead + cacheCreation */
  totalInputProcessed: number;
  /** Cache-miss "new" input tokens (tokens after last breakpoint) */
  newInputTokens: number;
  /** Tokens read from cache (cache hit) */
  cacheReadTokens: number;
  /** Tokens written to cache (cache creation) */
  cacheCreationTokens: number;

  // === Output Tokens (not cacheable, expensive) ===
  /** Output tokens generated by the model */
  outputTokens: number;

  // === Cache Efficiency (input-only — caching does NOT apply to output) ===
  /** Cache hit rate: cacheRead / totalInputProcessed (0~1, 0 if no input) */
  cacheHitRate: number;
  /** Whether any cache activity exists (read or creation > 0) */
  hasCache: boolean;
  /** Cost-weighted input: new×1.0 + creation×1.25 + read×0.1 */
  billableInputTokens: number;
  /**
   * Input cost savings vs. no-cache scenario: 1 - (billableInput / totalInputProcessed)
   * This is input-only because caching only affects input tokens.
   */
  inputSavingsPercent: number;

}

/**
 * Compute consistent metrics from TaskTokenUsage.
 */
export function getTokenUsageMetrics(tokenUsage?: TaskTokenUsage | null): TokenUsageMetrics {
  const newInputTokens = tokenUsage?.inputTokens || 0;
  const outputTokens = tokenUsage?.outputTokens || 0;
  const cacheReadTokens = tokenUsage?.cacheReadTokens || 0;
  const cacheCreationTokens = tokenUsage?.cacheCreationTokens || 0;

  // Input metrics
  const totalInputProcessed = newInputTokens + cacheReadTokens + cacheCreationTokens;

  // Cache efficiency (input-only)
  const hasCache = cacheReadTokens > 0 || cacheCreationTokens > 0;
  const cacheHitRate = totalInputProcessed > 0
    ? cacheReadTokens / totalInputProcessed
    : 0;

  const billableInputTokens =
    newInputTokens +
    Math.floor(cacheCreationTokens * CACHE_CREATION_MULTIPLIER) +
    Math.floor(cacheReadTokens * CACHE_READ_MULTIPLIER);

  // Input savings: how much cheaper billable input is vs full-price input
  const inputSavingsPercent = totalInputProcessed > 0
    ? Math.max(0, 1 - (billableInputTokens / totalInputProcessed))
    : 0;

  return {
    totalInputProcessed,
    newInputTokens,
    cacheReadTokens,
    cacheCreationTokens,
    outputTokens,
    cacheHitRate,
    hasCache,
    billableInputTokens,
    inputSavingsPercent,
  };
}

/**
 * Safely sum multiple TaskTokenUsage objects.
 * Returns undefined if no usage data exists.
 */
export function sumTokenUsages(usages: Array<TaskTokenUsage | undefined | null>): TaskTokenUsage | undefined {
  let hasAny = false;
  const acc: TaskTokenUsage = {
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    cacheReadTokens: 0,
    cacheCreationTokens: 0,
  };

  for (const u of usages) {
    if (!u) continue;
    hasAny = true;
    acc.inputTokens += u.inputTokens || 0;
    acc.outputTokens += u.outputTokens || 0;
    acc.totalTokens += u.totalTokens || 0;
    acc.cacheReadTokens = (acc.cacheReadTokens || 0) + (u.cacheReadTokens || 0);
    acc.cacheCreationTokens = (acc.cacheCreationTokens || 0) + (u.cacheCreationTokens || 0);
  }

  if (!hasAny) return undefined;

  const normalized: TaskTokenUsage = {
    inputTokens: acc.inputTokens,
    outputTokens: acc.outputTokens,
    totalTokens: acc.totalTokens,
  };
  if ((acc.cacheReadTokens || 0) > 0) normalized.cacheReadTokens = acc.cacheReadTokens;
  if ((acc.cacheCreationTokens || 0) > 0) normalized.cacheCreationTokens = acc.cacheCreationTokens;
  return normalized;
}

/**
 * Format a number compactly with max 3 displayed digits and at most 1 decimal place.
 *
 * Rule:
 *   - Integer part ≥ 3 digits → round to integer (no decimal)
 *   - Integer part < 3 digits → up to 1 decimal place (trailing .0 stripped)
 *
 * Examples:
 *   1     → "1"      ✓
 *   1.2   → "1.2"    ✓
 *   1.21  → "1.2"    ✓ (floor, max 1 decimal)
 *   20.19 → "20.1"   ✓ (floor, not 20.2)
 *   200   → "200"    ✓
 *   200.9 → "200"    ✓ (3-digit integer, floor to integer)
 */
export function formatCompactNumber(value: number): string {
  const abs = Math.abs(value);
  const intDigits = abs < 1 ? 1 : Math.floor(Math.log10(abs)) + 1;

  if (intDigits >= 3) {
    return Math.floor(abs).toString();
  }

  // Floor to 1 decimal place: Math.floor(1.29 * 10) / 10 = 1.2
  const floored = Math.floor(abs * 10) / 10;
  const str = floored.toFixed(1);
  return str.endsWith('.0') ? str.slice(0, -2) : str;
}

/**
 * Format token count with K/M/B/T notation (max 3 displayed digits)
 */
export function formatTokenCount(tokens: number): string {
  if (tokens === 0) return '0';
  const abs = Math.abs(tokens);
  if (abs >= 1_000_000_000_000) return `${formatCompactNumber(tokens / 1_000_000_000_000)}T`;
  if (abs >= 1_000_000_000) return `${formatCompactNumber(tokens / 1_000_000_000)}B`;
  if (abs >= 1_000_000) return `${formatCompactNumber(tokens / 1_000_000)}M`;
  if (abs >= 1_000) return `${formatCompactNumber(tokens / 1_000)}K`;
  return tokens.toString();
}

/**
 * Format percentage (0~1) as "XX.X%"
 */
export function formatPercent(ratio: number): string {
  return `${(ratio * 100).toFixed(1)}%`;
}

// ============================================
// Cost & Credit (precise, per-model)
// ============================================
//
// SSOT: `@ant/shared/pricing` (rate card) + `@ant/shared/billing` (markup /
// credit conversion). BE and FE share the same functions so the displayed
// USD cost and credit figure cannot drift from what the ledger debits. The
// legacy `billableInputTokens` (above) stays for the cache-efficiency gauge
// but is NOT the cost source — it was model-agnostic and ignored output rate.

/**
 * Precise USD list cost from a per-model breakdown (job-level). Prefer this
 * over the aggregate path — each model is priced at its own rate. Returns
 * undefined when no per-model data is available.
 */
export function costUsdFromByModel(byModel?: TokenUsageByModel | null): number | undefined {
  if (!byModel || Object.keys(byModel).length === 0) return undefined;
  return computeJobCostUsd(byModel).usd;
}

/** Precise USD list cost for ONE phase's usage at its model's rate. */
export function costUsdFromUsage(
  modelId: string | undefined,
  usage?: TaskTokenUsage | null,
): number | undefined {
  if (!usage || !modelId) return undefined;
  return computeCallCostUsdSafe(modelId, usage).usd;
}

/**
 * Customer-facing credits consumed for a given USD list cost. The `markup` is
 * server-driven (per-account, from the balance snapshot); defaults to 1 (no
 * markup) since the magnitude is a commercial value not shipped in the bundle.
 */
export function creditsFromUsd(usd: number, markup: number = 1): number {
  return microCreditsToCredits(usdToMicroCredits(usd, markup));
}

/**
 * One row of the per-model cost breakdown shown in the token-usage popup.
 * Each model is priced at its OWN rate (input / output / cache-write / cache-read),
 * so the popup can show exactly where the cost came from.
 */
export interface PerModelCostRow {
  modelId: string;
  inputTokens: number;
  outputTokens: number;
  cacheCreationTokens: number;
  cacheReadTokens: number;
  /** Precise USD list cost for this model's usage. */
  usd: number;
  /** Customer-facing credits (USD × markup), markup server-driven. */
  credits: number;
}

/**
 * Per-model cost rows from a job's per-model usage, sorted by cost desc. Uses
 * the shared rate card (`computeModelCostBreakdownUsd`) so each model's
 * cache-write / cache-read tokens are priced at their own rate — same SSOT the
 * ledger debits with. Empty when no per-model data.
 */
export function perModelCostRows(
  byModel?: TokenUsageByModel | null,
  markup: number = 1,
): PerModelCostRow[] {
  if (!byModel || Object.keys(byModel).length === 0) return [];
  const breakdown = computeModelCostBreakdownUsd(byModel);
  return Object.entries(byModel)
    .map(([modelId, u]) => {
      const usd = breakdown[modelId] ?? 0;
      return {
        modelId,
        inputTokens: u.inputTokens || 0,
        outputTokens: u.outputTokens || 0,
        cacheCreationTokens: u.cacheCreationTokens || 0,
        cacheReadTokens: u.cacheReadTokens || 0,
        usd,
        credits: creditsFromUsd(usd, markup),
      };
    })
    .sort((a, b) => b.usd - a.usd);
}

/**
 * Friendly short label for a model id (e.g. `claude-opus-4-8` → "Opus 4.8").
 * Falls back to the raw id for unknown models.
 */
export function formatModelLabel(modelId: string): string {
  const id = modelId.toLowerCase();
  if (id.includes('opus-4-8')) return 'Opus 4.8';
  if (id.includes('opus')) return 'Opus';
  if (id.includes('sonnet-4-6')) return 'Sonnet 4.6';
  if (id.includes('sonnet')) return 'Sonnet';
  if (id.includes('haiku-4-5')) return 'Haiku 4.5';
  if (id.includes('haiku')) return 'Haiku';
  return modelId;
}

/** Format a USD amount — sub-cent shows 4 decimals, else 2. */
export function formatUsd(usd: number): string {
  if (usd > 0 && usd < 0.01) return `$${usd.toFixed(4)}`;
  return `$${usd.toFixed(2)}`;
}

/** Format a credit amount compactly (e.g. "1.2K"). */
export function formatCredits(credits: number): string {
  if (credits > 0 && credits < 1) return credits.toFixed(2);
  return formatTokenCount(Math.round(credits));
}

/**
 * Format token usage as "input in · output out"
 * Uses billable input (cost-weighted) — what actually gets charged.
 */
export function formatTokenUsage(tokenUsage: TaskTokenUsage): string {
  const m = getTokenUsageMetrics(tokenUsage);
  return `${formatTokenCount(m.billableInputTokens)} in · ${formatTokenCount(m.outputTokens)} out`;
}

/**
 * Format compact token usage as "input in · output out"
 * Uses billable input (cost-weighted) for badges and compact displays.
 */
export function formatTokenUsageCompact(tokenUsage: TaskTokenUsage): string {
  const m = getTokenUsageMetrics(tokenUsage);
  return `${formatTokenCount(m.billableInputTokens)} in · ${formatTokenCount(m.outputTokens)} out`;
}
