import { ChatAnthropic } from "@langchain/anthropic";
import { getGitInstance, getCurrentBranch, getLatestCommit } from "../../../tools/git";
import { CodebaseAnalyzer } from "../analyzer/CodebaseAnalyzer";
import { storeCodebase, storeLearnings, logStoredData } from "../storage";
import { getDirectivePath, readDirective, generateReport } from "../utils";
import { DIRECTIVE_TYPES, ProjectContext, ArchitectResult } from "../types";

const model = new ChatAnthropic({
  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  model: "claude-3-haiku-20240307",
  temperature: 0.2,
  maxTokens: 4000
});

export async function handleLearnMode(context: ProjectContext): Promise<ArchitectResult> {
  console.log("\n" + "=".repeat(80));
  console.log("📚 LEARNING MODE");
  console.log("=".repeat(80));
  console.log(`\n🎯 Project: ${context.project}`);
  console.log(`📂 Feature: ${context.featureFolder || 'default'}`);
  console.log(`📅 Date: ${new Date().toISOString()}`);
  
  // 1. Git 정보 수집
  const git = await getGitInstance(context.project, context.config);
  const branchName = await getCurrentBranch(git);
  const commit = await getLatestCommit(git);
  
  // 2. 코드베이스 분석
  console.log(`📚 Analyzing codebase on branch "${branchName}"...`);
  const analyzer = new CodebaseAnalyzer(context.config.localPath);
  const nodes = await analyzer.analyze(context);
  
  // 3. 코드베이스 구조 저장
  const metadata = {
    project: context.project,
    branch: branchName,
    commitHash: commit.hash,
    timestamp: new Date().toISOString()
  };

  await storeCodebase(nodes, metadata, context.project);

  // 4. 디렉티브 기반 학습
  const directivePath = getDirectivePath(context, DIRECTIVE_TYPES.LEARN);
  const directive = readDirective(directivePath, DIRECTIVE_TYPES.LEARN);
  
  if (!directive) {
    throw new Error(`No learning directive found in: ${directivePath}\nCreate either directive.md or directive-N.md`);
  }

  const learningPrompt = `
You are analyzing code or architecture for learning and knowledge extraction.

Project: ${context.project}
Learning Directive:
${directive}

Extract key patterns, principles, and architectural decisions that should be remembered for future work.
Format your response as clear, categorized bullet points that can be stored as architectural principles.
`;

  const response = await model.invoke([{ role: "user", content: learningPrompt }]);
  const learnings = response.content as string;

  // 5. 학습 내용 저장
  await storeLearnings(learnings, context.project, context.featureFolder);

  // 6. 저장된 내용 출력
  logStoredData(metadata, nodes, learnings);

  // 7. 리포트 생성
  const reportContent = `# Learning Report
**Project:** ${context.project}
**Branch:** ${branchName}
**Commit:** ${commit.hash}
**Date:** ${new Date().toISOString()}

## Directive
${directive}

## Codebase Analysis
Total files analyzed: ${nodes.length}

### Files:
${nodes.map(node => `- ${node.path}`).join('\n')}

## Extracted Knowledge
${learnings}

---
*This report was automatically generated by the AI architecture agent.*
`;

  const reportFile = generateReport("learning", context, reportContent);
  
  console.log(`\n✅ Learned ${nodes.length} files from branch "${branchName}"`);
  console.log(`💡 Codebase structure and learnings stored in ChromaDB`);
  
  return {
    success: true,
    mode: 'learn',
    reportFile,
    filesAnalyzed: nodes.length,
    message: `Analysis completed and learnings stored in ChromaDB.`
  };
}
