/**
 * Design Document Types (UI + Game-Art surfaces)
 *
 * Type definitions for parsed design documents used in split injection.
 * Generated by Design Job and consumed by Code Job.
 *
 * Surface taxonomy (D24/D25):
 *   - 'ui'      → visual/ui/ant/{ui-tokens,ui-assets,ui-spec}.json
 *                 spec sub-section = chapter (header / main / footer / page)
 *   - 'gameArt' → visual/game-art/ant/{game-art-tokens,game-art-assets,game-art-spec}.json
 *                 spec sub-section = category dictionary (effects / characters / projectiles / npcs / ...)
 *                 (D24-revised v8 — sub-sourced canonical, mirrors visual/ui/ant)
 *
 * The two surfaces share the same JSON-dictionary parser shape — only the
 * semantics of sub-section keys differ, and the LLM picks those keys at
 * decompose time. Hence one parser, one structural type.
 *
 * NOTE: legacy aliases ParsedUiDocs / UiSpecSection / UiSpecTocEntry are
 * re-exported from `./uiDoc` for backward compatibility (Phase 2 → Phase 3).
 */

/**
 * Surface kind discriminator.
 * - 'ui'      : HUD / menu / control surface (chapter sub-sections)
 * - 'gameArt' : sprite / character / particle / audio surface (category dictionary)
 */
export type DesignDocSurface = 'ui' | 'gameArt';

/**
 * Individual section parsed from a *-spec.json document.
 * Surface-agnostic — only the sub-section semantics differ across surfaces.
 */
export interface DesignDocSection {
  /**
   * Semantic identifier dynamically discovered from spec.json keys at parse time.
   * - Container keys (all children are objects): split into "{key}-{childKey}"
   *   - UI:      "pages-events" / "modals-connectModal" / "sections-globalHeader"
   *   - GameArt: "effects-matchClear" / "characters-hero" / "projectiles-arrow"
   * - Leaf keys: used as-is (e.g. "meta", "layout").
   */
  id: string;

  /** Display title (mirrors the JSON path `key/childKey` or just `key`). */
  title: string;

  /** Heading level (always 2 for JSON-derived sections). */
  level: number;

  /** Pretty-printed JSON content of this section only. */
  content: string;

  /** Estimated token count for token-budget calculation. */
  tokenEstimate: number;

  /** Synthetic line range in the pretty-printed content `[start, end]`. */
  lineRange: [number, number];
}

/**
 * Lightweight TOC entry — used by decompose prompts to advertise available
 * sections without dumping full content.
 */
export interface DesignDocTocEntry {
  id: string;
  title: string;
  level: number;
  tokenEstimate: number;
}

/**
 * Parsed design documents for one surface (UI or GameArt).
 *
 * The structure is identical for both surfaces; the `surface` discriminator
 * tells consumers which interpretation to apply (e.g. UI's chapter ladder vs.
 * GameArt's category dictionary).
 */
export interface ParsedDesignDocs {
  /** Surface kind — informs prompt rendering, never auto-derived from path. */
  surface: DesignDocSurface;

  /**
   * Full content of `*-tokens.json` (typically small, ~5K tokens).
   * - UI:      ui-tokens.json — colors / typography / spacing
   * - GameArt: game-art-tokens.json — palette / silhouette / lighting / motionTone
   */
  tokens?: string;
  tokensTokenEstimate?: number;

  /**
   * Full content of `*-assets.json` (typically small, ~10K tokens).
   * - UI:      ui-assets.json — image / icon / logo mappings (external-only)
   * - GameArt: game-art-assets.json — category dictionary with `kind: 'inline' | 'external'`
   */
  assets?: string;
  assetsTokenEstimate?: number;

  /**
   * Parsed sections from `*-spec.json` — keyed by section id for O(1) lookup.
   * - UI:      chapters (page regions)
   * - GameArt: categories (asset kinds)
   */
  specSections: Map<string, DesignDocSection>;

  /** Document-order TOC for decompose prompt advertisement. */
  specToc: DesignDocTocEntry[];

  /** Sum of all section token estimates if all sections were inlined. */
  specTotalTokens: number;
}
