/**
 * UI Document Types
 * 
 * Type definitions for parsed UI documents used in split injection.
 * UI documents are generated by Design Job and consumed by Code Job.
 */

/**
 * Individual section from ui-spec.json
 * Represents a component or common section that can be independently injected
 */
export interface UiSpecSection {
  /**
   * Semantic identifier dynamically discovered from ui-spec.json keys at parse time.
   * - Container keys (all children are objects): split into "{key}-{childKey}"
   *   e.g., "pages-events", "modals-connectModal", "sections-globalHeader"
   * - Leaf keys: used as-is, e.g., "meta", "layout"
   */
  id: string;
  
  /**
   * Section title as it appears in the document
   * e.g., "### 1. GNB (Global Navigation Bar)"
   */
  title: string;
  
  /**
   * Section heading level (2 for ##, 3 for ###)
   */
  level: number;
  
  /**
   * Full content of the section including subsections
   */
  content: string;
  
  /**
   * Estimated token count for this section
   * Used for token budget calculation
   */
  tokenEstimate: number;
  
  /**
   * Line range in the original file [startLine, endLine]
   * Useful for debugging and source mapping
   */
  lineRange: [number, number];
}

/**
 * Parsed UI documents structure
 * Result of parsing ui-spec.json, ui-tokens.json, ui-assets.json
 */
export interface ParsedUiDocs {
  /**
   * Full content of ui-tokens.json (usually small, ~5K tokens)
   * Contains design tokens: colors, typography, spacing, etc.
   */
  tokens?: string;
  
  /**
   * Estimated token count for tokens document
   */
  tokensTokenEstimate?: number;
  
  /**
   * Full content of ui-assets.json (usually small, ~10K tokens)
   * Contains asset mappings grouped by user-defined categories
   */
  assets?: string;
  
  /**
   * Estimated token count for assets document
   */
  assetsTokenEstimate?: number;
  
  /**
   * Parsed sections from ui-spec.json
   * Indexed by section ID for quick lookup
   */
  specSections: Map<string, UiSpecSection>;
  
  /**
   * Table of contents for ui-spec.json
   * Used in decompose prompt to show available sections without full content
   */
  specToc: UiSpecTocEntry[];
  
  /**
   * Total estimated tokens if all spec sections are combined
   */
  specTotalTokens: number;
}

/**
 * Table of contents entry for ui-spec.json
 * Lightweight representation for decompose prompt
 */
export interface UiSpecTocEntry {
  /**
   * Section ID matching UiSpecSection.id
   */
  id: string;
  
  /**
   * Section title
   */
  title: string;
  
  /**
   * Heading level (2 or 3)
   */
  level: number;
  
  /**
   * Estimated token count
   */
  tokenEstimate: number;
}

