/**
 * UI Document Types
 * 
 * Type definitions for parsed UI documents used in split injection.
 * UI documents are generated by Design Job and consumed by Code Job.
 */

/**
 * Individual section from ui-spec.json
 * Represents a component or common section that can be independently injected
 */
export interface UiSpecSection {
  /**
   * Semantic identifier for the section
   * - Component sections: "gnb", "hero", "about", "ecosystem", "token", "technology", "social", "footer"
   * - Common sections: "layout", "overview", "responsive", "accessibility", "grid", "performance"
   */
  id: string;
  
  /**
   * Section title as it appears in the document
   * e.g., "### 1. GNB (Global Navigation Bar)"
   */
  title: string;
  
  /**
   * Section heading level (2 for ##, 3 for ###)
   */
  level: number;
  
  /**
   * Full content of the section including subsections
   */
  content: string;
  
  /**
   * Estimated token count for this section
   * Used for token budget calculation
   */
  tokenEstimate: number;
  
  /**
   * Line range in the original file [startLine, endLine]
   * Useful for debugging and source mapping
   */
  lineRange: [number, number];
}

/**
 * Parsed UI documents structure
 * Result of parsing ui-spec.json, ui-tokens.json, ui-assets.json
 */
export interface ParsedUiDocs {
  /**
   * Full content of ui-tokens.json (usually small, ~5K tokens)
   * Contains design tokens: colors, typography, spacing, etc.
   */
  tokens?: string;
  
  /**
   * Estimated token count for tokens document
   */
  tokensTokenEstimate?: number;
  
  /**
   * Full content of ui-assets.json (usually small, ~10K tokens)
   * Contains asset mappings: logos, icons, backgrounds, etc.
   */
  assets?: string;
  
  /**
   * Estimated token count for assets document
   */
  assetsTokenEstimate?: number;
  
  /**
   * Parsed sections from ui-spec.json
   * Indexed by section ID for quick lookup
   */
  specSections: Map<string, UiSpecSection>;
  
  /**
   * Table of contents for ui-spec.json
   * Used in decompose prompt to show available sections without full content
   */
  specToc: UiSpecTocEntry[];
  
  /**
   * Total estimated tokens if all spec sections are combined
   */
  specTotalTokens: number;
}

/**
 * Table of contents entry for ui-spec.json
 * Lightweight representation for decompose prompt
 */
export interface UiSpecTocEntry {
  /**
   * Section ID matching UiSpecSection.id
   */
  id: string;
  
  /**
   * Section title
   */
  title: string;
  
  /**
   * Heading level (2 or 3)
   */
  level: number;
  
  /**
   * Estimated token count
   */
  tokenEstimate: number;
}

/**
 * Standard section ID mapping
 * Maps various title patterns to canonical section IDs
 */
export const UI_SECTION_ID_MAP: Record<string, string> = {
  // Component sections (from ### N. Component Name)
  'gnb': 'gnb',
  'global navigation bar': 'gnb',
  'header': 'gnb',
  'hero': 'hero',
  'hero section': 'hero',
  'about': 'about',
  'about section': 'about',
  'ecosystem': 'ecosystem',
  'ecosystem section': 'ecosystem',
  'token': 'token',
  'token section': 'token',
  'technology': 'technology',
  'technology section': 'technology',
  'social': 'social',
  'social section': 'social',
  'footer': 'footer',
  'footer section': 'footer',
  
  // Common sections (from ## N. Section Name)
  'overview': 'overview',
  'layout': 'layout',
  'layout structure': 'layout',
  'component specifications': 'components',
  'responsive': 'responsive',
  'responsive behavior': 'responsive',
  'responsive layout grid': 'responsive',
  'accessibility': 'accessibility',
  'accessibility requirements': 'accessibility',
  'performance': 'performance',
  'performance and optimization': 'performance',
  'performance and optimization considerations': 'performance',
  'grid': 'grid',
};

/**
 * Default sections to always include for UI tasks
 * These provide essential context regardless of specific component
 */
export const UI_DEFAULT_SECTIONS = ['overview', 'layout', 'tokens'];

/**
 * Component sections that can be individually requested
 */
export const UI_COMPONENT_SECTIONS = [
  'gnb', 'hero', 'about', 'ecosystem', 'token', 'technology', 'social', 'footer'
];

/**
 * Common sections that provide shared specifications
 */
export const UI_COMMON_SECTIONS = [
  'overview', 'layout', 'responsive', 'accessibility', 'grid', 'performance'
];
